---
# Source: repo-chart/templates/namespace.yaml
# Namespace for repo server
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: repo
  name: repo

---
# Source: repo-chart/templates/config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mindspore-configmap
  namespace: repo
data:
  update-repo-job.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: update-repo-job
      namespace: repo
    spec:
      template:
        spec:
          containers:
            - name: update-repo
              image: swr.cn-north-1.myhuaweicloud.com/hwstaff_h00223369/repo-tools:0.0.1
              # NOTE: PROJECT_VARIABLE is used to be replaced with actual project list, don't update this only at this place.
              args: ["--repo-json", "PROJECT_VARIABLE", "update"]
              volumeMounts:
                - mountPath: /repo/mindspore
                  name: repo-data-volume
              env:
                - name: WORKING_DIR
                  value: /repo/mindspore/repository
          restartPolicy: Never
          volumes:
            - name: repo-data-volume
              persistentVolumeClaim:
                claimName: mindspore-data-volume
  default.conf: |
    server {
        listen 443 ssl;
  
        access_log  /var/log/nginx/host.access.log  main;
  
        server_name repo.mindspore.cn;
        ssl on;
        ssl_certificate /etc/nginx/ssl/fullchain.pem;
        ssl_certificate_key  /etc/nginx/ssl/privkey.pem;
  
        location /repository {
            root   /repo/mindspore;
            autoindex   on;
        }
  
        error_page   500 502 503 504  /50x.html;
  
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
  
  nginx.conf: |-
    user  root;
    worker_processes  1;
  
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
  
  
    events {
        worker_connections  1024;
    }
  
  
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
  
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
  
        access_log  /var/log/nginx/access.log  main;
  
        sendfile        on;
        #tcp_nopush     on;
  
        keepalive_timeout  65;
  
        #gzip  on;
  
        include /etc/nginx/conf.d/*.conf;
    }
  


---
# Source: repo-chart/templates/deployment.yaml
# Persistent volume claim for deployment
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mindspore-data-volume
  namespace: repo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: sas

# ServiceAccount for deployment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mindspore-listener
  namespace: repo
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mindspore-listener
rules:
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mindspore-listener
subjects:
  - kind: ServiceAccount
    name: mindspore-listener
    namespace: repo
roleRef:
  kind: ClusterRole
  name: mindspore-listener
  apiGroup: rbac.authorization.k8s.io


# Deployment for repo service
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mindspore
  namespace: repo
  labels:
    app: repo-nginx-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: repo-nginx-pod
  template:
    metadata:
      labels:
        app: repo-nginx-pod
    spec:
      serviceAccount: mindspore-listener
      initContainers:
        - name: repo-prepare-tool
          image: swr.cn-north-1.myhuaweicloud.com/hwstaff_h00223369/repo-tools:0.0.1
          env:
            # key and cert file used for nginx tls
            - name: KEY_FILE
              value: https://mindspore-internal.obs.cn-north-1.myhuaweicloud.com:443/server.key?AccessKeyId=YZVVEL6NEL42V1E1PN2I&Expires=1576070298&response-content-disposition=inline&x-obs-security-token=gQpjbi1ub3J0aC00jveIGix17BmlJlivODF2FiuzzJgDw2jY9IZYF-73zGq9jr6QlzUSDm-ILC0Exf0jDwsUb_tu4IAw0uwIpXpHtn1P2vMrPBrBy2E6oxgX0f7x6q2G37Ye92g_hLVUcsSm6K_RcBoJiuj1wB3QLiCH_jTsJq1dGh3dfQxySsYG56eHcG69Y8pJ9LowpIyi4DNzCsSfKPfB5RA8OwIxjiC0PhuDJnNp4PePaL50KbHH_fa8Kr1rk1vEmqMbsRfffTr0KZ4kxbaco5I3zq-slQ3OvUXdoS0WWWtYFpxxbF7H-vpbUa4EHWDzpXg4ASTV07YAIYJt_iLw7VaMZIJST4_9rIds8qmUdKLG0BPFHW9ARYGrrBVdQlOBBNC5yJ5UE7o6jppOZ_FBAmvCI2nWoSTEaBFyVEGc21m0SElzeF5fThRF6b3M1TKyQTi28d6WZEvCrtPilAC-FJnH4fsKKpxBmjm2udi5PDH7SO3-nPGlblA9DtnIDjME2J3a0kfUACrr8I1YALa_EYalqWM6w7HANhT58PHsZ801oO6b6NieYtCx4J3cXOuIxyRIwc52xjs05rE3GQbUpJ5RTzqQahYSyhnaA1gPh6LsBgD9R_BMaG9Zrng2EZQnSnUQZGmd0imGXvBuugxD3Tc7W4iSsZF70i-6TT788h54IeWg4T4jpF6roAkJXrgv2h0Mx6UhogtVCp8-kcXHu3qDHLN1RnJWpk2csgHYIP5UIXryyTvBjEGuJqugVuI4I3hoZA34-IyWGQGVwlhNaPGqMnvnYoV09B61sgcJjmSr-s3T2F57GPzNcOKqjVmbT6kA3u-3QIkNnA%3D%3D&Signature=KWBpHjQ4RN2VNJcoovrdOy9/Fts%3D
            - name: CERT_FILE
              value: https://mindspore-internal.obs.cn-north-1.myhuaweicloud.com:443/server.crt?AccessKeyId=XNF6ZORN21BQO7LPNU2C&Expires=1576070275&response-content-disposition=inline&x-obs-security-token=gQpjbi1ub3J0aC00jiX0NtbqsbEVW7j5qflAei1gbcBAPbe9ChXuj0WE8WXcOyV_wOAtxZVuqZRT5ufu0kisNcOI6Kdc08GmfNm4JiT3XELLRP62tGxYEIyPGAEA1n6YbLAdBrVbXAiuMDyItySf0KBTMVAEzpRlgPsFTduaT3ZS1JJDkoaY5tkbiZ1OgjA_VXxcUVLBDfr3oGYe08vVaZB61Ln_MsyRP9dvN-vkmjqcXP-8vUWo9vC8fF-f8CYBL59W_VX_aq6AX6hadRcjzthr9j-4svIRBRZjcgMFlhjl2Ay1gIbg-BB9UnJYAzd9j9GJu1v3oFAgY2PXP0Fcn1l0aEtVLz1uV-UHALfcFm2mexIYFqTug-FdQR8QOQiqILbVadWg_CF71exaJunTptyD0kQobKRyHPD8UNGcz_Xsh5WVWR-EeQ_sf3deSYXlzsuiTYWpNeEluxgIqWN1LxP3kiIcCbfBI0xobZkblX7ISOvP7CGZVh48vXxHVn6UE6HXrCNBReoY4JZOdEJW1MlY-sZQCsCHJWbsWJ93Oc9xaFlaf1gFRvBvY5WMGqlSsQRE125UiKOytfZKFAJqZU9daBzeCbep3HZxmF1zIilgMLBbDyMJtFtQWTfEpTquSreRUXuqjAUq8VZul6LgM8D2IGnBFq2LchSgTL36W60dpAMTka57lgbJVyQY7mUpe9mgO593grJeHcVcCGFWxw1xHNmALyBD_0v0AGeFwnVRsvvHH1JKqo6thqejUry4Pkdf5yXXFYIzUeqwFX75S-t-niOudp70_oZo6b3WyayBLyQxuPzcKqsNNpYBNukXPm5g14mUhbK4NyX3Zg%3D%3D&Signature=aC5wl78O28C6RW25BO/iDLQ6g20%3D
          args: ["--key-file", "$(KEY_FILE)","--cert-file", "$(CERT_FILE)", "prepare"]
          volumeMounts:
            - mountPath: /etc/nginx/ssl
              name: repo-nginx-tls-volume
      containers:
        - name: repo-nginx
          image: swr.cn-north-1.myhuaweicloud.com/hwstaff_h00223369/nginx:1.17.5
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /etc/nginx/ssl
              name: repo-nginx-tls-volume
            - mountPath: /etc/nginx/nginx.conf
              name: repo-nginx-configmap-volume
              subPath: nginx.conf
            - mountPath: /etc/nginx/conf.d/default.conf
              name: repo-nginx-configmap-volume
              subPath: default.conf
            - mountPath: /repo/mindspore
              name: repo-data-volume
        - name: repo-update-listener
          image: swr.cn-north-1.myhuaweicloud.com/hwstaff_h00223369/repo-listener:0.0.1
          env:
              # base auth for repo listener
            - name: BASIC_AUTH_USERNAME
              value: mindspore
            - name: BASIC_AUTH_PASSWORD
              value: mindspore
            - name: K8S_NAMESPACE
              value: repo
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /etc/repo-update/update-repo-job.yaml
              name: repo-nginx-configmap-volume
              subPath: update-repo-job.yaml
      volumes:
        - name: repo-nginx-tls-volume
          emptyDir: {}
        - name: repo-nginx-configmap-volume
          configMap:
            name: mindspore-configmap
        - name: repo-data-volume
          persistentVolumeClaim:
            claimName: mindspore-data-volume

---
# Source: repo-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mindspore-service
  namespace: repo
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: 3bcca11e-b0cb-40f2-a751-17a8b25b9774
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 443
      name: nginx-repo-https
      targetPort: 443
    - port: 80
      name: nginx-repo-listener-http
      targetPort: 80
  selector:
    app: repo-nginx-pod
  type: LoadBalancer
  loadBalancerIP: 119.3.241.57
