---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: argocd-cert-secrets
  namespace: argocd
spec:
  name: argocd-cert-secrets
  keysMap:
    server_crt:
      path: secrets/data/mindspore/website-secrets
      key: server.crt
    server_key:
      path: secrets/data/mindspore/website-secrets
      key: server.key