---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: vault-secret
  namespace: vault
spec:
  name: vault-secret
  keysMap:
    server_crt:
      path: secrets/data/mindspore/website-secrets
      key: server.crt
    server_key:
      path: secrets/data/mindspore/website-secrets
      key: server.key
