apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-file-backend
  namespace: vault
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: sas
  volumeMode: Filesystem

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config-map
  namespace: vault
data:
  config.hcl: |

    storage "file" {
      path = "/root/file"
    }

    listener "tcp" {
      address     = "127.0.0.1:8200"
      tls_disable = 1
    }

    telemetry {
      statsite_address = "127.0.0.1:8125"
      disable_hostname = true
    }
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
  namespace: vault
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: d7ff3b09-a34c-413f-a8c3-9eff8ed25b27
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 117.78.48.76
  type: LoadBalancer
  ports:
    - name: vault
      port: 80
      targetPort: 8200
      protocol: TCP
  selector:
    app: vault

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: vault
  name: vault
  namespace: vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - image: swr.cn-north-1.myhuaweicloud.com/hwstaff_h00223369/vault:1.3.0
          name: vault
          ports:
            - containerPort: 8200
              name: vaultport
              protocol: TCP
          volumeMounts:
            - name: vault-config
              mountPath: /valut/config/config.hcl
              subPath: config.hcl
            - name: vault-file
              mountPath: /valut/file
      volumes:
        - name: vault-file
          persistentVolumeClaim:
            claimName: vault-file-backend
        - name: vault-config
          configMap:
            name: vault-config-map
