---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: botinfo
  namespace: bot
  labels:
    app: botinfo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.nginxinfod: semver:~1.0
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: botinfo
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: botinfo
    spec:
      #this node selector used to select the node that will serve as backend host for mindspore website elb, for the "/cla" stuff.
      nodeSelector:
        botnode: "true"
      containers:
      - name: botinfod
        image: mindspore/ci-bot:0.0.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /bot/
          name: configmap-volume
      volumes:
      - name: configmap-volume
        configMap:
          name: bot-configmap
