---
apiVersion: v1
kind: Service
metadata:
  name: botservice
  namespace: bot
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: 5f440e52-97b7-4e4a-9a62-86193cf45f10
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 119.3.240.10
  ports:
    - name: httpport
      protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 31200
  selector:
    app: botinfo
  type: LoadBalancer
