---
apiVersion: v1
kind: Service
metadata:
  name: botservice
  namespace: bot
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: 7d53ff7e-5fbb-4a86-84fb-444c647a2fa1
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 121.36.29.195
  ports:
    - name: httpport
      protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 31200
  selector:
    app: botinfo
  type: LoadBalancer
