---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-sync-manager
  namespace: secrets-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-sync-manager
rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "update"
      - "delete"
      - "create"
  - apiGroups:
      - "secrets-manager.tuenti.io"
    resources:
      - "secretdefinitions"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "update"
      - "delete"
      - "create"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-sync-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-sync-manager
subjects:
  - kind: ServiceAccount
    name: secret-sync-manager
    namespace: secrets-manager

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: secret-sync-manager
  namespace: secrets-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secrets-manager
  template:
    metadata:
      labels:
        app: secrets-manager
    spec:
      serviceAccountName: secret-sync-manager
      containers:
        - image: swr.cn-north-1.myhuaweicloud.com/hwstaff_h00223369/secrets-manager:v1.0.2
          imagePullPolicy: IfNotPresent
          name: secrets-manager
          args:
            - -vault.url=https://dev-secrets.mindspore.cn/
            - -enable-debug-log
          env:
            - name: VAULT_ROLE_ID
              valueFrom:
                secretKeyRef:
                  name: vault-approle-secret
                  key: role_id
            - name: VAULT_SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: vault-approle-secret
                  key: secret_id
      restartPolicy: Always
