---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mindspore-jenkins
  namespace: jenkins
spec:
  name: mindspore-jenkins
  keysMap:
    jenkins-admin-user:
      path: secrets/data/mindspore/jenkins_secrets
      key: jenkins-admin-user
    jenkins-admin-password:
      path: secrets/data/mindspore/jenkins_secrets
      key: jenkins-admin-password
    jenkins-user-password:
      path: secrets/data/mindspore/jenkins_secrets
      key: jenkins-user-password

