# Resource for small specification slave pods
apiVersion: v1
kind: Service
metadata:
  name: small-slaves-service
  labels:
    app: small-slaves
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: small-slaves

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: small-slaves
  namespace: default
  labels:
    app: small-slaves
spec:
  serviceName: small-slaves-service
  replicas: 2
  selector:
    matchLabels:
      app: small-slaves
  template:
    metadata:
      labels:
        app: small-slaves
    spec:
      containers:
        - name: slave-init
          image: tommylike/jenkins-slave-tools:0.0.1
          env:
            - name: JENKINS_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_USER_NAME
              value: admin
            - name: JENKINS_USER_PASSWORD
              value: 11bbcf7dfa50b83cf1fe8773acfb527fc7
            - name: JENKINS_AGENT_WORKDIR
              value: /home/jenkins/agent-working-dir
            - name: JENKINS_URL
              value: http://mindspore-jenkins.default.svc.cluster.local:80
            - name: JENKINS_SHARE_FOLDER
              value: /home/jenkins/share-folder
            - name: EXECUTOR_NUMBERS
              value: 4
            - name: NODE_LABELS
              value: x86;small
          args: ["$(JENKINS_URL)", "$(JENKINS_USER_NAME)", "$(JENKINS_USER_PASSWORD)", "$(JENKINS_NODE_NAME)", "$(EXECUTOR_NUMBERS)", "$(WORKING_DIR)", "$(NODE_LABELS)", "$(JENKINS_SHARE_FOLDER)"]
        - name: jenkins-slave
          image: alpine:3.10
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /home/jenkins/agent-working-dir
              name: jenkins-workspace
            - mountPath: /home/jenkins/share-folder
              name: jenkins-share-folder
          command:
            - /bin/sh
            - -c
            - |
              sleep 10000;
          env:
            - name: JENKINS_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_SECRET
              value: 623648f4686a7a0cc32530f6ba09b731f0993c348bd429266f327131fde49b6a
            - name: JENKINS_TUNNEL
              value: mindspore-jenkins-agent:50000
            - name: JENKINS_AGENT_NAME
              value: k8s-x86-gl02w
            - name: JENKINS_NAME
              value: k8s-x86-gl02w
            - name: JENKINS_AGENT_WORKDIR
              value: /home/jenkins/agent-working-dir
            - name: JENKINS_URL
              value: http://mindspore-jenkins.default.svc.cluster.local:80

      volumes:
        - name: jenkins-workspace
          emptyDir: {}
        - name: jenkins-share-folder
            emptyDir: {}
