---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mailman-secrets
  namespace: mail
spec:
  name: mailman-secrets
  keysMap:
    hyperkitty_api_key:
      path: secrets/data/mindspore/mail_secrets
      key: hyperkitty_api_key
    mailman_core_password:
      path: secrets/data/mindspore/mail_secrets
      key: mailman_core_password
    mailman_core_user:
      path: secrets/data/mindspore/mail_secrets
      key: mailman_core_user
    secret_key:
      path: secrets/data/mindspore/mail_secrets
      key: secret_key
    postgres_user:
      path: secrets/data/mindspore/mail_secrets
      key: postgres_user
    postgres_password:
      path: secrets/data/mindspore/mail_secrets
      key: postgres_password
