name: Publish Docker images
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: mindspore/ubuntu-gpu
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
        dockerfile: development/jenkins/dockerfile/slaves/ubuntu-gpu/Dockerfile
        workdir: development/jenkins/dockerfile/slaves/ubuntu-gpu
