---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: hmac-token
  namespace: prow
spec:
  name: hmac-token
  keysMap:
    hmac:
      path: secrets/data/mindspore/prow
      key: hmac_secret
---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: oauth-token
  namespace: prow
spec:
  name: oauth-token
  keysMap:
    hmac:
      path: secrets/data/mindspore/prow
      key: github_token
